### ISSUE TITLE
Shiny Application Not Exposing Port 3838 in Docker Swarm

### ISSUE THREAD

**Issue by samvaltenbergs** [rocker-org/geospatial#18]
Hi @cboettig and @eddelbuettel... Firstly, thank you for all the Rocker images you guys put together, they're fantastic. Also, I apologize as this isn't really an issue with the Rocker image, but the firewall security at my employer prevents me from posting (although I can view) on Stack Overflow so I am hoping I can make some progress here...

We have been using the `geospatial` image for close to a year now and it had been working fine. We host multiple Shiny applications on a Docker EE swarm, using Traefik as a reverse proxy. Recently, upon redeploying a Shiny application with a minor R parameter change the URL for this Shiny application started returning "Bad Gateway." There are a bunch of other Shiny applications running on the swarm, but all of a sudden if we deploy (or redeploy) anything new we get a bad gateway error. We are quite confused and have been looking at this for a week: our Docker installation hasn't been updated since August, Traefik has been frozen since February and the R/Shiny code in question has also been frozen since June.

One quirky phenomenon is that we can access the RStudio server application for the particular deployment but not a Shiny application. That is, if I go to implementation.qa.gswarm.XXX.com I get a bad gateway error. If I redeploy the application and open up Traefik port 8787 instead of 3838 and go to  implementation.qa.gswarm.XXX.com then RStudio server comes up without any issues. 

I can see on the docker_gwbridge bridge network that the implementation_qa_pm_app is registered as a container, and I can see that Traefik is up and running for this container/service like it is for all the other applications we have running. We really have no idea why our Shiny deployment started failing even though we are unaware of anything changing "under the hood..."

Here is the application's stack file:
```
version: '3'

services:
  pm_app:
    image: gitlab.XXX.com:5005/gaashiny/implementationreport:${APP_ENV}  
    environment:
      - APP_ENV=${APP_ENV}
    volumes:
      - /sfofileserver/global:/sfofileserver/global
    networks:
      - traefik_public
    deploy:
      placement:
        constraints: 
          - node.hostname == mcsfvlidokas01d.XXX.com
      mode: replicated
      replicas: 1
      labels:
        traefik.port: 3838
        traefik.frontend.rule: Host:implementation.${APP_ENV}.gswarm.XXX.com
        traefik.docker.network: traefik_public

networks:
  traefik_public:
    external: true
```

The `start_shiny.sh` file:

```
#!/bin/bash
echo "export GAAMAHI_APP_ENV=$APP_ENV" >> /etc/profile
eval "$@"
```

And the `shiny-server.conf` file:

```
run_as shiny;

server {
  listen 3838;

  location / {

    app_dir /srv/shiny-server/implementation;

    log_dir /sfofileserver/global/srv/implementation/log;

  }
}
```

Sorry for blasting this out on here, but we're really scratching our heads on this so any ideas would be most appreciated...
